{
  parserClass="com.jeremyworboys.expressionengine.parser.ExpressionEngineParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="ExpressionEngine"
  psiImplClassSuffix="Impl"
  psiPackage="com.jeremyworboys.expressionengine.psi"
  psiImplPackage="com.jeremyworboys.expressionengine.psi.impl"

  elementTypeHolderClass="com.jeremyworboys.expressionengine.psi.ExpressionEngineTypes"
  elementTypeClass="com.jeremyworboys.expressionengine.psi.ExpressionEngineElementType"
  tokenTypeClass="com.jeremyworboys.expressionengine.psi.ExpressionEngineTokenType"
}

expressionengineFile ::= statement*
private statement ::= (tag|HTML|COMMENT|CRLF)

tag ::= LD tag_name tag_content RD
tag_name ::= (TAG_BUILTIN|TAG_ADDON|TAG_CONSTANT|TAG_DEPRECATED|TAG_GLOBAL_VAR|IDENTIFIER)
tag_content ::= attribute*

attribute ::= CRLF? IDENTIFIER EQUAL (NUMBER|IDENTIFIER|attribute_string) CRLF?
attribute_string ::= (STRING_START STRING+ STRING_END) | (STRING_START STRING_END)
//attribute_string ::= (STRING_START ((tag_block|tag|i18nFormat) | STRING+)+ STRING_END) | (STRING_START STRING_END)
