{
  parserClass="com.jeremyworboys.expressionengine.parser.ExpressionEngineParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="ExpressionEngine"
  psiImplClassSuffix="Impl"
  psiPackage="com.jeremyworboys.expressionengine.psi"
  psiImplPackage="com.jeremyworboys.expressionengine.psi.impl"

  elementTypeHolderClass="com.jeremyworboys.expressionengine.psi.ExpressionEngineTypes"
  elementTypeClass="com.jeremyworboys.expressionengine.psi.ExpressionEngineElementType"
  tokenTypeClass="com.jeremyworboys.expressionengine.psi.ExpressionEngineTokenType"
}

expressionengineFile ::= statement*
private statement ::= (tag|HTML|COMMENT|CRLF)

tag ::= LD tag_name RD
tag_name ::= IDENTIFIER
